name: lint

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependency
        run: pip install pre-commit==3.5.0
      - name: Install pre-commit
        run: pre-commit install
      - name: Run pre-commit
        run: pre-commit run --all-files
